backend/models/Vtum.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "vtum".
 *
 * @property int $id
 * @property int $vid
 * @property int $tumsoato
 * @property int $vresid
 * @property string $driver
 * @property int $vac_all
 * @property string $car
 * @property int $status
 * @property int $user
 * @property string $created
 * @property string $updated
 */
class Vtum extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vtum';
    }
	
	public $pinfl;
	public $serial;
	
	public $cartype;
	public $carnumber;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vvid', 'vid', 'vilsoato', 'tumsoato', 'vresid', 'vac_all', 'car', 'status', 'user', 'cartype', 'carnumber', 'serialv'], 'required', 'message' => '{attribute} тўлдирилиши лозим'],
			[['driver'], 'required', 'message' => 'Хайдовчи маълумотлари нотўғри киритилган'],
            [['vvid', 'vid', 'vilsoato', 'tumsoato', 'vresid', 'vac_all', 'status', 'user'], 'integer'],
            [['driver', 'car', 'serialv'], 'string'],
            [['created', 'updated'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'vvid' => Yii::t('app', 'Вилоятга кирим рақами'),
            'vid' => Yii::t('app', 'Вацина'),
			'serialv' => Yii::t('app', 'Серия рақами'),
            'tumsoato' => Yii::t('app', 'Туман'),
            'vilsoato' => Yii::t('app', 'Вилоят'),
            'vresid' => Yii::t('app', 'Кирим рақами'),
            'driver' => Yii::t('app', 'Eтказиб бериш учун маъсул'),
            'vac_all' => Yii::t('app', 'Вакцина миқдори'),
            'car' => Yii::t('app', 'Транспорт'),
            'status' => Yii::t('app', 'Ҳолат'),
            'user' => Yii::t('app', 'Тарқатди'),
            'created' => Yii::t('app', 'Тарқатилган сана'),
            'updated' => Yii::t('app', 'Янгиланган сана'),
			'pinfl' => Yii::t('app', 'Хайдовчи ЖШШИР'), 
            'serial' => Yii::t('app', 'Паспорт серияси ва рақами'), 
            'cartype' => Yii::t('app', 'Вакцина ташувчи тарнспорт тури'), 
            'carnumber' => Yii::t('app', 'Тарнспорт рақами'), 
        ];
    }
	
	public function getTuman()
    {
        return $this->hasOne(Regions::className(), ['code' => 'tumsoato']);
    }
	
	public function getRegion()
    {
        return $this->hasOne(Regions::className(), ['code' => 'vilsoato']);
    }
	
	public function getVaccine()
    {
        return $this->hasOne(Vaccine::className(), ['id' => 'vid']);
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;
use backend\models\SignupForm;
use backend\models\ResendVerificationEmailForm;
use backend\models\VerifyEmailForm;
use app\models\Profiles;
use app\models\Vuch;
use app\models\User;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'signup', 'checklogin'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'signup'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
	
	public function beforeAction( $action ) {
		if ( parent::beforeAction ( $action ) ) {

			 //change layout for error action after 
			 //checking for the error action name 
			 //so that the layout is set for errors only
			if ( $action->id == 'error' ) {
				$this->layout = 'error';
			}
			return true;
		} 
	}

	public function actionChecklogin()	
    {	
        if(null !== Yii::$app->request->get('username')){			
			$user = User::find()->where(['username' => Yii::$app->request->get('username')])->asArray()->COUNT();									
		}
		elseif(null !== Yii::$app->request->get('email')){			
			$user = User::find()->where(['email' => Yii::$app->request->get('email')])->asArray()->COUNT();									
		}
		
	  
			  
		if($user == 1){
			if(null !== Yii::$app->request->get('username')){			
				return 	"Ушбу логин тизимда мавжуд. Бошка логинни танланг";  
			}
			elseif(null !== Yii::$app->request->get('email')){			
				return 	"Ушбу электрон манзил тизимда мавжуд. Бошка электрон манзилни танланг";  
			}
		}
		else{
			return 	1;  
		}
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
	
	public function actionSignup()
    {
		if(Yii::$app->user->getIsGuest()){
			$this->layout = "blank";
			$model = new SignupForm();
			$profiles = new Profiles();
			if($model->load(Yii::$app->request->post()) AND $profiles->load(Yii::$app->request->post())) {
				if ($user = $model->signup()) {				
					$profiles->id = $user->id;
					if($profiles->save()){
						if (Yii::$app->getUser()->login($user)) {
							return $this->goHome();
						}
					}
					else{
						return print_r($profiles);
					}					
				}
			}

			return $this->render('signup', [
				'model' => $model,
				'profiles' => $profiles,
			]);
		}
		else{
			return $this->goHome();
		}
    }
	
	

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use app\models\Profiles;
use app\models\Vuch;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];		
    }
	
	public function checkuser()
		{
			if(Yii::$app->user->isGuest){
				$this->redirect(['login']);
			}
		}

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {		
		 if(Yii::$app->user->isGuest){
				  return $this->redirect(['site/login']);
			}
		
		$profiles = Profiles::findOne(Yii::$app->user->identity->id);
		$vuch = Vuch::find()->where(['uchastka' => $profiles->uchastka])->limit(3)->all();
		
		
        return $this->render('index', [
                'vuch' => $vuch,
            ]);
    }
	
	 public function actionNoaccess()
    {		
		$this->layout = 'noaccess';
		if(Yii::$app->user->isGuest){
		  return $this->redirect(['site/login']);
		}
		
        return $this->render('noaccess');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
		$this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }
}

frontend/views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Profiles;
use app\models\Vuch;

$profiles = Profiles::findOne(Yii::$app->user->identity->id);
$model = new Vuch();
// Список инструкции		
$vuch = Vuch::find()->where(['uchastka' => $profiles->uchastka])->andWhere(['status' => 1])->all();
/* @var $this yii\web\View */
/* @var $model app\models\Vuch */
/* @var $form yii\widgets\ActiveForm */
?>


    <?php $form = ActiveForm::begin(['action' => '/vuch/recieve', 'method' => 'post']); ?>

	<div class="input-wrapper">
        <label class="label" for="account1">Кимдан ва қанча</label>
        <select class="form-control custom-select" name="Vuch[vtum]" id="vtum">
		<option selected="selected">Вакцинани танланг</option>
			<?php foreach($vuch as $uchval):?>
				<?php $driver = json_decode($uchval->driver, true); ?>					
					<option value="<?= $uchval->id; ?>" id="<?= $uchval->vac_all; ?>"><?= $uchval->vaccine['name']; ?> (<?= $uchval->vac_all; ?> доза) - <?= $driver['data']['inf']['surname_latin']; ?> <?= $driver['data']['inf']['name_latin']; ?> <?= $driver['data']['inf']['patronym_latin']; ?>.</option>
				<?php endforeach;?>
        </select>
    </div></br>    

    <?= $form->field($model, 'vac_recieved')->textInput(['type' => 'number', 'max' => 999, 'min' => 1]) ?>

	<div class="form-group basic">
        <label> <input type="checkbox" id="agreerecieve"> Вакциналарни қабул қилдим ва келгусида ушбу вакциналар жавобгарлигини ўз зиммамга оламан.</label>                                    
    </div>

    <div class="form-group basic">		  
        <?= Html::submitButton('Қабул қилдим', ['class' => 'btn-c btn-primary btn-block btn-lg', 'id' => 'buttonagree', 'disabled' => 'disabled']) ?>    		
    </div>		
	<?php ActiveForm::end(); ?>
	
	
<?php 
$this->registerJs(<<<JS
	$('#vtum').change(function(){
		//alert($(this).val());
		var dropd = document.getElementById("vtum");
		document.getElementById('vuch-vac_recieved').value=dropd.options[dropd.selectedIndex].id;		
		document.getElementById('vuch-vac_recieved').max=dropd.options[dropd.selectedIndex].id;		
	});
	
	$('#agreerecieve').click(function(){
		var checkBox = document.getElementById("agreerecieve");

		if(checkBox.checked == true){
			var vac = document.getElementById('vuch-vac_recieved').value;
			var dropd = document.getElementById("vtum");
			var vacid = dropd.options[dropd.selectedIndex].id;		
			if(vac > 0 && vacid > 0){
				document.getElementById("buttonagree").disabled = false;
			}			
		}else{
			document.getElementById("buttonagree").disabled = true;
		}
	});
	
	

JS
);
?>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = 'Саҳифа топилмади';
?>
 
    <div class="balance-area pd-top-40">
        <div class="container">            
					<h1>404 ҳато</h1>
					<div class="alert alert-danger">
						Саҳифа топилмади
					</div>
					<p>        
						Юқоридаги хатолик веб-сервер сизнинг сўровингизга ишлов бераётганда юз берди 
					</p>                
        </div>
    </div>

frontend/views/site/index.php
<?php
use app\models\Vdoc;
/* @var $this yii\web\View */
$vdocs = Vdoc::find()->all();
$this->title = 'VIS-REGISTON - Эпизоотияга қарши курашиш тадбирлари мониторинг тизими';
?>
<!-- add balance start -->
    <div class="add-balance-area">
        <div class="container">
		
			<a href="/vaccination/create">
				<div class="ba-add-balance-title style-two">
					<h5>Вакцина ишлатиш</h5>
					<i class="fa fa-plus"></i>
				</div>
			</a></br>
		
            <div class="ba-add-balance-title ba-add-balance-btn">
                <h5>Вакцина қабул қилиш</h5>
                <i class="fa fa-plus"></i>
            </div>			
            <div class="ba-add-balance-inner mg-top-40">
                <div class="row custom-gutters-20">
                    <div class="col-6">
                        <a class="btn btn-blue" href="/vuch/new">Янги вакциналар <i class="fa fa-arrow-down"></i></a>
                    </div>
					<div class="col-6">
                        <a class="btn btn-green" href="/vuch/recieved">Қабул қилинганлари<i class="fa fa-arrow-down"></i></a>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-red" href="/vaccination/spended">Сарфланганлари <i class="fa fa-arrow-right"></i></a>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-purple" href="/vaccination/balance ">Қолдиқ <i class="fa fa-credit-card-alt "></i></a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- add balance End -->

    <!-- goal area Start -->
    <div class="goal-area pd-top-36">
        <div class="container">
            <div class="section-title">
                <h3 class="title">Вақциналар рўйхати</h3>
                <a href="/vuch/">Тўлиқ рўйхат</a> 
            </div>
			<?php foreach($vuch as $val):?>
			<div class="single-goal <?php if($val->status == 1): ?>single-goal-three<?php elseif($val->status == 2): ?>single-goal-one<?php endif; ?>">
                <div class="row">
                    <div class="col-7 pr-0">
                        <div class="details">
                            <h6><?php echo $val->vaccine['name']; ?> [ <?php echo $val->vaccine['code']; ?> ]</h6>
                            <?php if($val->status == 1): ?><p>Қабул қилинмаган</p><?php else: ?><p>Қабул қилинган санаси: <?= $val->date_recieved; ?></p><?php endif; ?>
                        </div>
                    </div>
                    <div class="col-5 pl-0">
                        <div class="circle-inner circle-inner-one">
                            <h6 class="goal-amount"> <?php echo $val->vac_all; ?> доза</h6>                            
                        </div>
                    </div>
                </div>
            </div>
			<?php endforeach; ?>            
        </div>
    </div>
    <!-- goal area End -->
	
	    <!-- blog-area start -->
    <div class="blog-area pd-top-36 pb-2 mg-top-40" style="background-image: url(/assets/img/bg/6.png);">
        <div class="container">
            <div class="section-title">
                <h3 class="title">Қўлланмалар</h3>
                <a href="/vdoc">Барчасини кўриш</a>
            </div>
            <div class="blog-slider owl-carousel">
			<?php foreach($vdocs as $val): ?>
                <div class="item">
                    <div class="single-blog">
                        <div class="thumb">
                            <img src="/assets/img/blog/1.png" alt="img">
                        </div>
                        <div class="details">
                            <a href="/vdoc/view?id=<?= $val->id; ?>"><?= $val->vaccine['name']; ?> [<?= $val->vaccine['code']; ?>] вакцинасини эмлаш учун қўлланма</a>
                        </div>
                    </div>
                </div>
			<?php endforeach; ?>	                
            </div>
        </div>
    </div>
    <!-- blog-area End -->

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Тизимга кириш';
$this->params['breadcrumbs'][] = $this->title;
?>
    <h1><?= Html::encode($this->title) ?></h1>

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true])->label('Логин'); ?>

                <?= $form->field($model, 'password')->passwordInput()->label('Калит сўз'); ?>
              
                <div class="form-group">
                    <?= Html::submitButton('Тизимга кириш', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>

frontend/views/site/noaccess.php
<?php
use app\models\Vdoc;
use yii\helpers\Html;

$vdocs = Vdoc::find()->all();
$this->title = 'VIS-REGISTON - Эпизоотияга қарши курашиш тадбирлари мониторинг тизими';
?>
<!-- add balance start -->
    <div class="add-balance-area">
        <div class="container">
			Сизда ушбу тизимдан фойдаланиш ваколати мавжуд эмас<br/>
<?= Html::a('<i class="feather icon-power text-danger"></i> Тизимдан чиқиш', ['site/logout'], ['data' => ['confirm' => 'Сиз ушбу тизимдан чиқиб бошқа логин билан кириш имконига эгасиз!', 'method' => 'POST'], 'class' => 'btn btn-danger']) ?>			
        </div>
    </div>
    <!-- add balance End -->

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Vuch */

$this->title = 'Update Vuch: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Vuches', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="vuch-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>